[package]
name = "patrie"
version = "0.0.1"
authors = ["theseriousadult <jack@gallabytes.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"
description = "a trie which skips single-child nodes"

[dependencies]
